name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  working-directory:
    description: working directory to pass to pre-commit
    required: false
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
    working-directory: ${{ inputs.working-directory }}
  - run: python -m pip freeze --local
    shell: bash
    working-directory: ${{ inputs.working-directory }}
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles(format('{0}/.pre-commit-config.yaml', inputs.working-directory)) }}
  - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
